server:
  port: 28081  # 用户服务端口（避免Windows端口限制）

spring:
  application:
    name: user-service  # 服务名称

  # Nacos配置将在第一阶段统一添加
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  #       namespace: public
  #       group: DEFAULT_GROUP
  #       username: ${NACOS_USERNAME:nacos}
  #       password: ${NACOS_PASSWORD:nacos}
  #     config:
  #       server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  #       file-extension: yml
  #       namespace: public
  #       group: DEFAULT_GROUP
  #       username: ${NACOS_USERNAME:nacos}
  #       password: ${NACOS_PASSWORD:nacos}

  # 数据库和Redis配置将在第三阶段统一启用
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce}
  #   username: ${DB_USERNAME:root}
  #   password: ${DB_PASSWORD:root123456}

  # data:
  #   redis:
  #     host: ${REDIS_HOST:localhost}
  #     port: ${REDIS_PORT:6379}
  #     password: ${REDIS_PASSWORD:}
  #     database: 0

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL日志
  global-config:
    db-config:
      logic-delete-field: deleted  # 逻辑删除字段
      logic-delete-value: 1  # 逻辑删除值
      logic-not-delete-value: 0  # 逻辑未删除值

# 日志配置
logging:
  level:
    com.cao.ecommerce: DEBUG
    com.cao.ecommerce.user.mapper: DEBUG  # Mapper接口SQL日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always