# ==========================================
# 电商微服务基础设施服务
# Infrastructure Services for E-commerce Microservices
# ==========================================

services:
  # MySQL数据库
  mysql:
    image: ${MYSQL_IMAGE:-mysql}:${MYSQL_VERSION:-8.0}
    container_name: ecommerce-mysql
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root123456}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ecommerce}
      - MYSQL_USER=${MYSQL_USER:-ecommerce}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-ecommerce123}
      - MYSQL_CHARACTER_SET_SERVER=${MYSQL_CHARSET:-utf8mb4}
      - MYSQL_COLLATION_SERVER=${MYSQL_COLLATION:-utf8mb4_unicode_ci}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - ecommerce-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=${MYSQL_CHARSET:-utf8mb4}
      --collation-server=${MYSQL_COLLATION:-utf8mb4_unicode_ci}
      --explicit_defaults_for_timestamp=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root123456}"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=database"

  # Redis缓存
  redis:
    image: ${REDIS_IMAGE:-redis}:${REDIS_VERSION:-7.0-alpine}
    container_name: ecommerce-redis
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - ecommerce-network
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-30}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=cache"

  # Nacos服务注册发现和配置中心
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION:-v2.5.1}
    container_name: ecommerce-nacos
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - MODE=${NACOS_MODE:-standalone}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE:-true}
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=${MYSQL_PORT:-3306}
      - MYSQL_SERVICE_DB_NAME=${NACOS_DB_NAME:-nacos_config}
      - MYSQL_SERVICE_USER=${NACOS_DB_USER:-root}
      - MYSQL_SERVICE_PASSWORD=${NACOS_DB_PASSWORD:-root123456}
      - MYSQL_CHARACTER_SET_SERVER=${MYSQL_CHARSET:-utf8mb4}
      - MYSQL_COLLATION_SERVER=${MYSQL_COLLATION:-utf8mb4_unicode_ci}
      - NACOS_SERVER_PORT=${NACOS_SERVER_PORT:-8848}
      - NACOS_APPLICATION_PORT=${NACOS_SERVER_PORT:-8848}
      - NACOS_SERVER_RPC_PORT=${NACOS_SERVER_RPC_PORT:-9848}
    ports:
      - "${NACOS_SERVER_PORT:-8848}:${NACOS_SERVER_PORT:-8848}"
      - "${NACOS_SERVER_RPC_PORT:-9848}:${NACOS_SERVER_RPC_PORT:-9848}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./logs/nacos:/home/nacos/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NACOS_SERVER_PORT:-8848}/nacos"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=service-registry"

  # RocketMQ NameServer
  rocketmq-nameserver:
    image: ${ROCKETMQ_IMAGE:-apache/rocketmq}:${ROCKETMQ_VERSION:-5.3.2}
    container_name: ecommerce-rocketmq-nameserver
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m -Duser.timezone=${TIMEZONE:-Asia/Shanghai}
    ports:
      - "${ROCKETMQ_NAMESRV_PORT:-9876}:${ROCKETMQ_NAMESRV_PORT:-9876}"
    networks:
      - ecommerce-network
    volumes:
      - rocketmq-nameserver-logs:/home/rocketmq/logs
      - /etc/localtime:/etc/localtime:ro
    command: ["sh","-c","./mqnamesrv"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "tail -f /dev/null"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-30}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=message-queue"

  # RocketMQ Broker
  rocketmq-broker:
    image: ${ROCKETMQ_IMAGE:-apache/rocketmq}:${ROCKETMQ_VERSION:-5.3.2}
    container_name: ecommerce-rocketmq-broker
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m -Duser.timezone=${TIMEZONE:-Asia/Shanghai}
      - NAMESRV_ADDR=rocketmq-nameserver:${ROCKETMQ_NAMESRV_PORT:-9876}
    ports:
      - "${ROCKETMQ_BROKER_PORT1:-10909}:${ROCKETMQ_BROKER_PORT1:-10909}"
      - "${ROCKETMQ_BROKER_PORT2:-10911}:${ROCKETMQ_BROKER_PORT2:-10911}"
    depends_on:
      rocketmq-nameserver:
        condition: service_started
    networks:
      - ecommerce-network
    volumes:
      - rocketmq-broker-logs:/home/rocketmq/logs
      - rocketmq-broker-store:/home/rocketmq/store
      - /etc/localtime:/etc/localtime:ro
    command: ["sh","-c","./mqbroker -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "tail -f /dev/null"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-30}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=message-queue"

  # RocketMQ Console
  rocketmq-console:
    image: ${ROCKETMQ_CONSOLE_IMAGE:-styletang/rocketmq-console-ng}:${ROCKETMQ_CONSOLE_VERSION:-latest}
    container_name: ecommerce-rocketmq-console
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-nameserver:${ROCKETMQ_NAMESRV_PORT:-9876} -Dcom.rocketmq.sendMessageWithVIPChannel=false
    ports:
      - "${ROCKETMQ_CONSOLE_PORT:-8081}:8080"
    depends_on:
      rocketmq-nameserver:
        condition: service_started
    networks:
      - ecommerce-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=message-queue"

  # Seata分布式事务协调器
  seata-server:
    image: ${SEATA_IMAGE:-seataio/seata-server}:${SEATA_VERSION:-2.0.0}
    container_name: ecommerce-seata
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - SEATA_PORT=${SEATA_SERVER_PORT:-7091}
      - STORE_MODE=${SEATA_STORE_MODE:-db}
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    ports:
      - "${SEATA_SERVER_PORT:-7091}:${SEATA_SERVER_PORT:-7091}"
      - "${SEATA_SERVER_RPC_PORT:-8091}:${SEATA_SERVER_RPC_PORT:-8091}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./config/seata:/root/seata-config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SEATA_SERVER_PORT:-7091}/"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=infrastructure"
      - "com.ecommerce.service.category=transaction"

networks:
  ecommerce-network:
    driver: bridge
    name: ecommerce-infrastructure-network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mysql-data:
    driver: local
    name: ecommerce-mysql-data
  redis-data:
    driver: local
    name: ecommerce-redis-data
  rocketmq-nameserver-logs:
    driver: local
    name: ecommerce-rocketmq-nameserver-logs
  rocketmq-broker-logs:
    driver: local
    name: ecommerce-rocketmq-broker-logs
  rocketmq-broker-store:
    driver: local
    name: ecommerce-rocketmq-broker-store