# ==========================================
# 电商微服务应用服务
# Application Services for E-commerce Microservices
# ==========================================

services:
  # API网关服务
  api-gateway:
    build:
      context: ../../backend/api-gateway
      dockerfile: Dockerfile
    image: ecommerce/api-gateway:latest
    container_name: api-gateway
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPTS=${GATEWAY_JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -Duser.timezone=${TIMEZONE:-Asia/Shanghai}}
      - NACOS_SERVER_ADDR=nacos:${NACOS_SERVER_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
    ports:
      - "${GATEWAY_PORT:-28080}:28080"
    networks:
      - ecommerce-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28080/actuator/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=application"
      - "com.ecommerce.service.category=gateway"
      - "com.ecommerce.service.tier=frontend"

  # 用户服务
  user-service:
    build:
      context: ../../backend/user-service
      dockerfile: Dockerfile
    image: ecommerce/user-service:latest
    container_name: user-service
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPTS=${USER_SERVICE_JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -Duser.timezone=${TIMEZONE:-Asia/Shanghai}}
      - NACOS_SERVER_ADDR=nacos:${NACOS_SERVER_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT:-3306}
      - DB_NAME=${MYSQL_DATABASE:-ecommerce}
      - DB_USERNAME=${MYSQL_USER:-root}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-root123456}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123456}
    ports:
      - "${USER_SERVICE_PORT:-28081}:28081"
    networks:
      - ecommerce-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28081/actuator/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=application"
      - "com.ecommerce.service.category=business"
      - "com.ecommerce.service.domain=user"
      - "com.ecommerce.service.tier=backend"

  # 商品服务
  product-service:
    build:
      context: ../../backend/product-service
      dockerfile: Dockerfile
    image: ecommerce/product-service:latest
    container_name: product-service
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPTS=${PRODUCT_SERVICE_JAVA_OPTS:--Xms512m -Xmx1536m -XX:+UseG1GC -XX:+UseContainerSupport -Duser.timezone=${TIMEZONE:-Asia/Shanghai}}
      - NACOS_SERVER_ADDR=nacos:${NACOS_SERVER_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT:-3306}
      - DB_NAME=${MYSQL_DATABASE:-ecommerce}
      - DB_USERNAME=${MYSQL_USER:-root}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-root123456}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123456}
    ports:
      - "${PRODUCT_SERVICE_PORT:-28082}:28082"
    networks:
      - ecommerce-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28082/actuator/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=application"
      - "com.ecommerce.service.category=business"
      - "com.ecommerce.service.domain=product"
      - "com.ecommerce.service.tier=backend"

  # 交易服务
  trade-service:
    build:
      context: ../../backend/trade-service
      dockerfile: Dockerfile
    image: ecommerce/trade-service:latest
    container_name: trade-service
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JAVA_OPTS=${TRADE_SERVICE_JAVA_OPTS:--Xms512m -Xmx1536m -XX:+UseG1GC -XX:+UseContainerSupport -Duser.timezone=${TIMEZONE:-Asia/Shanghai}}
      - NACOS_SERVER_ADDR=nacos:${NACOS_SERVER_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT:-3306}
      - DB_NAME=${MYSQL_DATABASE:-ecommerce}
      - DB_USERNAME=${MYSQL_USER:-root}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-root123456}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123456}
      - ROCKETMQ_NAMESERVER_ADDR=rocketmq-nameserver:${ROCKETMQ_NAMESRV_PORT:-9876}
    ports:
      - "${TRADE_SERVICE_PORT:-28083}:28083"
    networks:
      - ecommerce-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28083/actuator/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30}s
      timeout: ${HEALTHCHECK_TIMEOUT:-10}s
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-60}s
    labels:
      - "com.ecommerce.service.type=application"
      - "com.ecommerce.service.category=business"
      - "com.ecommerce.service.domain=trade"
      - "com.ecommerce.service.tier=backend"

networks:
  ecommerce-network:
    external: true
    name: ecommerce-network