version: '3.8'

services:
  # Nacos服务注册发现和配置中心
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: ecommerce-nacos
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root123456
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    networks:
      - ecommerce-network
    volumes:
      - ./logs/nacos:/home/nacos/logs
    restart: unless-stopped

  # MySQL数据库
  mysql:
    image: mysql:8.0.40
    container_name: ecommerce-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_DATABASE=ecommerce
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7.0-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

  # RocketMQ NameServer
  rocketmq-nameserver:
    image: apache/rocketmq:5.3.2
    container_name: ecommerce-rocketmq-nameserver
    environment:
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m
    ports:
      - "9876:9876"
    networks:
      - ecommerce-network
    volumes:
      - rocketmq-nameserver-logs:/home/rocketmq/logs
    command: ["sh","-c","./mqnamesrv"]
    restart: unless-stopped

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: ecommerce-rocketmq-broker
    environment:
      - JAVA_OPT_EXT=-server -Xms256m -Xmx256m
      - NAMESRV_ADDR=rocketmq-nameserver:9876
    ports:
      - "10909:10909"
      - "10911:10911"
    networks:
      - ecommerce-network
    volumes:
      - rocketmq-broker-logs:/home/rocketmq/logs
      - rocketmq-broker-store:/home/rocketmq/store
    command: ["sh","-c","./mqbroker -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf"]
    depends_on:
      - rocketmq-nameserver
    restart: unless-stopped

  # RocketMQ Console
  rocketmq-console:
    image: styletang/rocketmq-console-ng:latest
    container_name: ecommerce-rocketmq-console
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-nameserver:9876
    ports:
      - "8081:8080"
    networks:
      - ecommerce-network
    depends_on:
      - rocketmq-nameserver
    restart: unless-stopped

  # Seata分布式事务协调器
  seata-server:
    image: seataio/seata-server:2.0.0
    container_name: ecommerce-seata
    environment:
      - SEATA_PORT=7091
      - STORE_MODE=db
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    ports:
      - "7091:7091"
      - "8091:8091"
    networks:
      - ecommerce-network
    volumes:
      - ./config/seata:/root/seata-config
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  rocketmq-nameserver-logs:
    driver: local
  rocketmq-broker-logs:
    driver: local
  rocketmq-broker-store:
    driver: local